# Nom du workflow, ici j'ai mis le nom en fonction de ce qu'on a au labo à la question3
name: Construire le conteneur et le publier sur le registre GitHub Packages

# Déclencheur du workflow, ici on veut que le workflow soit déclenché à chaque fois qu'on push sur la branche main
on:
  push:
    branches:
      - main

# Les jobs du workflow, ici on a un job qui s'appelle "build"
jobs:
  build:
    # Environnement d'exécution : machine virtuelle Linux
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write

    steps:
      # Étape 1 : Récupère le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure Docker Buildx pour des fonctionnalités avancées de build
      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Se connecter au GitHub Docker Registry
      - name: Se connecter au GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io # Registre de conteneurs de GitHub
          username: ${{ github.actor }} # On utilise le nom de l'utilisateur GitHub qui a déclenché le workflow
          password: ${{ secrets.GITHUB_TOKEN }} # On utilise le token secret pour se connecter au registre GitHub Packages(token généré dans GitHub)

      # Étape 4 : Construire le conteneur et le publier sur le registre GitHub Packages
      - name: Construire le conteneur et le publier sur le registre GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: . # Utilise le répertoire courant pour construire l'image
          push: true
          tags: ghcr.io/luffy0xcyber/ue19-lab-05/my-app:latest # identifiant de l'image Docker taguée

      # Étape 5 : Scanner l'image Docker pour les vulnerabilites
      - name: Scanner l'image Docker pour les vulnerabilites
        uses: aquasecurity/trivy-action@master # On utilise l'action "trivy" pour scanner l'image Docker
        with:
          image-ref: ghcr.io/luffy0xcyber/ue19-lab-05/my-app:latest